[package]
name = "pinnacle-config"
version = "0.1.0"
edition = "2024"

[dependencies]
pinnacle-api = { git = "http://github.com/cassandracomar/pinnacle", branch = "fix/rockspec-path", default-features = false }

[features]
default = ["snowcap"]
snowcap = ["pinnacle-api/snowcap"]
